# ==============================================================================
# docker-compose
# ==============================================================================
version: '3'
services:
  # ----------------------------------------------------------------------------
  develop: &dev-base
  # ----------------------------------------------------------------------------
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: /bin/bash
    links:
      - postgres
    environment:
      LANG: 'C.UTF-8'
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - secrets.env
    volumes:
      - .:/go/src/clicker-back
    stdin_open: true
    tty: true


  # ----------------------------------------------------------------------------
  app:
  # ----------------------------------------------------------------------------
    <<: *dev-base
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    ports:
      - '8000:8000'
    command: go run main.go


  # ----------------------------------------------------------------------------
  postgres:
  # ----------------------------------------------------------------------------
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data


# ----------------------------------------------------------------------------
volumes:
# ----------------------------------------------------------------------------
  postgres-data: {}
